@startuml
'https://plantuml.com/sequence-diagram
actor "In/Output"
database "file json"
participant java.io
control Main
"file json" <-> Main : read data
Main -> MyCollection : load
MyCollection <- MyCollection : sort

"In/Output" -> java.io : InputStreamReader

java.io -> Main : command
Main <-> MyCollection : input validate

Main -> Main : command exe cycle

Main -> MyCollection : request
Main <- MyCollection : response

java.io <- Main : response

"In/Output" <- java.io : PrintWriter





@enduml